name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    # 使用预构建的Docker镜像，包含完整的Flutter SDK
    container:
      image: cirrusci/flutter:stable
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 依赖项和构建步骤
      - name: Get dependencies
        run: flutter pub get

      - name: Generate protobuf files
        run: flutter pub run build_runner build

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error