name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.6'

      - name: Enable flutter caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Get dependencies
        run: flutter pub get || true

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Generate dependency report in HTML
        run: |
          flutter pub deps --json > deps.json || true
          python3 - <<'EOF'
          import json, sys

          try:
              deps = json.load(open("deps.json"))
          except Exception:
              deps = {"packages": []}

          html = "<table border='1' style='border-collapse:collapse;'><tr><th>Package</th><th>Version</th><th>Status</th></tr>"

          for dep in deps.get("packages", []):
              name = dep.get("name", "")
              version = dep.get("version", "")
              # 检查版本冲突
              if dep.get("dependency") == "transitive":
                  status = "<span style='color:orange'>transitive</span>"
              elif version == "":
                  status = "<span style='color:red'>missing</span>"
              else:
                  status = "<span style='color:green'>ok</span>"
              html += f"<tr><td>{name}</td><td>{version}</td><td>{status}</td></tr>"

          html += "</table>"

          with open("deps.html", "w") as f:
              f.write(html)
          EOF

      - name: Add dependency report to GitHub Actions summary
        run: cat deps.html >> $GITHUB_STEP_SUMMARY

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
