name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/flutter
            ~/.pub-cache
          key: flutter-sdk-${{ runner.os }}-3.24.3
          restore-keys: |
            flutter-sdk-${{ runner.os }}-

      - name: Set up Flutter
        id: flutter-setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Use a known stable version
          channel: 'stable'
          cache: true
          cache-key: flutter-sdk-${{ runner.os }}-3.24.3
          cache-path: ~/flutter

      - name: Debug Flutter installation
        run: |
          echo "Flutter SDK path:"
          ls -la ~/flutter
          ls -la ~/flutter/bin
          ls -la ~/flutter/bin/cache/dart-sdk/bin/snapshots/ || echo "Snapshots directory not found"
          echo "PATH:"
          echo $PATH
          echo "Flutter version:"
          ~/flutter/bin/flutter --version || echo "Flutter binary not found"

      - name: Verify Flutter installation
        run: |
          export PATH="$HOME/flutter/bin:$PATH"
          flutter doctor -v
          flutter precache --force
          flutter pub cache repair

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Clean build artifacts
        run: flutter clean

      - name: Generate protobuf files
        run: flutter pub run build_runner build --delete-conflicting-outputs --verbose

      - name: Build APK
        run: flutter build apk --release --split-per-abi --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error