name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 强制清除Flutter缓存，以解决SDK文件损坏问题
      - name: Clear Flutter cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/flutter

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.2'

      # 新增这一步，用于重新生成protobuf文件
      - name: Generate protobuf files
        run: flutter pub run build_runner build

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error