name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.2'

      - name: Fix Gradle wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Create local properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties

      - name: Get dependencies
        run: flutter pub get

      - name: Clean build
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error